/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IFuroVesting, IFuroVestingInterface } from "../IFuroVesting";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "vestId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "ownerAmount",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "recipientAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "contract IERC20",
        name: "token",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "toBentoBox",
        type: "bool",
      },
    ],
    name: "CancelVesting",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "vestId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "contract IERC20",
        name: "token",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "start",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "cliffDuration",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "stepDuration",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "steps",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "cliffAmount",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "uint128",
        name: "stepAmount",
        type: "uint128",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "fromBentoBox",
        type: "bool",
      },
    ],
    name: "CreateVesting",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "vestId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "LogUpdateOwner",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "vestId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "contract IERC20",
        name: "token",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "toBentoBox",
        type: "bool",
      },
    ],
    name: "Withdraw",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "contract IERC20",
        name: "token",
        type: "address",
      },
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        internalType: "uint32",
        name: "start",
        type: "uint32",
      },
      {
        internalType: "uint32",
        name: "cliffDuration",
        type: "uint32",
      },
      {
        internalType: "uint32",
        name: "stepDuration",
        type: "uint32",
      },
      {
        internalType: "uint32",
        name: "steps",
        type: "uint32",
      },
      {
        internalType: "uint128",
        name: "cliffAmount",
        type: "uint128",
      },
      {
        internalType: "uint128",
        name: "stepAmount",
        type: "uint128",
      },
      {
        internalType: "bool",
        name: "fromBentoBox",
        type: "bool",
      },
    ],
    name: "createVesting",
    outputs: [
      {
        internalType: "uint256",
        name: "depositedShares",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "vestId",
        type: "uint256",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "bool",
        name: "approved",
        type: "bool",
      },
      {
        internalType: "uint8",
        name: "v",
        type: "uint8",
      },
      {
        internalType: "bytes32",
        name: "r",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "s",
        type: "bytes32",
      },
    ],
    name: "setBentoBoxApproval",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "vestId",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "toBentoBox",
        type: "bool",
      },
    ],
    name: "stopVesting",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "vestId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "updateOwner",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "vestId",
        type: "uint256",
      },
    ],
    name: "vestBalance",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "vestId",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "taskData",
        type: "bytes",
      },
      {
        internalType: "bool",
        name: "toBentoBox",
        type: "bool",
      },
    ],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IFuroVesting__factory {
  static readonly abi = _abi;
  static createInterface(): IFuroVestingInterface {
    return new utils.Interface(_abi) as IFuroVestingInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IFuroVesting {
    return new Contract(address, _abi, signerOrProvider) as IFuroVesting;
  }
}
