/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IFuroStream, IFuroStreamInterface } from "../IFuroStream";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "streamId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "senderBalance",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "recipientBalance",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "toBentoBox",
        type: "bool",
      },
    ],
    name: "CancelStream",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "streamId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "startTime",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "endTime",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "fromBentoBox",
        type: "bool",
      },
    ],
    name: "CreateStream",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "streamId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint128",
        name: "topUpAmount",
        type: "uint128",
      },
      {
        indexed: true,
        internalType: "uint64",
        name: "extendTime",
        type: "uint64",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "fromBentoBox",
        type: "bool",
      },
    ],
    name: "UpdateStream",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "streamId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "sharesToWithdraw",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "withdrawTo",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "toBentoBox",
        type: "bool",
      },
    ],
    name: "Withdraw",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "streamId",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "toBentoBox",
        type: "bool",
      },
    ],
    name: "cancelStream",
    outputs: [
      {
        internalType: "uint256",
        name: "senderBalance",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "recipientBalance",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "uint64",
        name: "startTime",
        type: "uint64",
      },
      {
        internalType: "uint64",
        name: "endTime",
        type: "uint64",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "fromBento",
        type: "bool",
      },
    ],
    name: "createStream",
    outputs: [
      {
        internalType: "uint256",
        name: "streamId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "depositedShares",
        type: "uint256",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "streamId",
        type: "uint256",
      },
    ],
    name: "getStream",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "sender",
            type: "address",
          },
          {
            internalType: "address",
            name: "token",
            type: "address",
          },
          {
            internalType: "uint128",
            name: "depositedShares",
            type: "uint128",
          },
          {
            internalType: "uint128",
            name: "withdrawnShares",
            type: "uint128",
          },
          {
            internalType: "uint64",
            name: "startTime",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "endTime",
            type: "uint64",
          },
        ],
        internalType: "struct IFuroStream.Stream",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "bool",
        name: "approved",
        type: "bool",
      },
      {
        internalType: "uint8",
        name: "v",
        type: "uint8",
      },
      {
        internalType: "bytes32",
        name: "r",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "s",
        type: "bytes32",
      },
    ],
    name: "setBentoBoxApproval",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "streamId",
        type: "uint256",
      },
    ],
    name: "streamBalanceOf",
    outputs: [
      {
        internalType: "uint256",
        name: "senderBalance",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "recipientBalance",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "streamId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
    ],
    name: "updateSender",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "streamId",
        type: "uint256",
      },
      {
        internalType: "uint128",
        name: "topUpAmount",
        type: "uint128",
      },
      {
        internalType: "uint64",
        name: "extendTime",
        type: "uint64",
      },
      {
        internalType: "bool",
        name: "fromBentoBox",
        type: "bool",
      },
    ],
    name: "updateStream",
    outputs: [
      {
        internalType: "uint256",
        name: "depositedShares",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "streamId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "sharesToWithdraw",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "withdrawTo",
        type: "address",
      },
      {
        internalType: "bool",
        name: "toBentoBox",
        type: "bool",
      },
      {
        internalType: "bytes",
        name: "taskData",
        type: "bytes",
      },
    ],
    name: "withdrawFromStream",
    outputs: [
      {
        internalType: "uint256",
        name: "recipientBalance",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IFuroStream__factory {
  static readonly abi = _abi;
  static createInterface(): IFuroStreamInterface {
    return new utils.Interface(_abi) as IFuroStreamInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IFuroStream {
    return new Contract(address, _abi, signerOrProvider) as IFuroStream;
  }
}
