/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { ITasker, ITaskerInterface } from "../ITasker";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "onTaskReceived",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ITasker__factory {
  static readonly abi = _abi;
  static createInterface(): ITaskerInterface {
    return new utils.Interface(_abi) as ITaskerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITasker {
    return new Contract(address, _abi, signerOrProvider) as ITasker;
  }
}
